# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-20 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='actionoperations',
            new_name='action_operations',
        ),
        migrations.RenameField(
            model_name='actionoperation',
            old_name='userprofiles',
            new_name='user_profiles',
        ),
    ]
