# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-13 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='monitor_by',
            field=models.CharField(choices=[('agent', '客户端'), ('snmp', 'SNMP')], max_length=64, verbose_name='监控方式'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.IntegerField(choices=[(1, '在线'), (2, '宕机'), (3, '未知'), (4, '下线'), (5, '问题')], default=3, verbose_name='主机状态'),
        ),
    ]
