# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='应用集名称')),
                ('plugin_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='插件名称')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '应用集表',
            },
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='IP')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名称')),
                ('monitor_by', models.CharField(choices=[('agent', 'Agent'), ('snmp', 'SNMP')], max_length=64, verbose_name='监控方式')),
                ('status', models.IntegerField(choices=[(1, '在线'), (2, '宕机'), (3, '未知'), (4, '下线'), (5, '问题')], verbose_name='主机状态')),
                ('host_alive_check_interval', models.IntegerField(default=30, verbose_name='主机存活状态检测间隔')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
        migrations.CreateModel(
            name='HostsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='主机组名称')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '主机组表',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='监控项名称')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='键值')),
                ('interval', models.IntegerField(default=60, verbose_name='监控间隔')),
                ('data_type', models.CharField(choices=[('int', '整数'), ('float', '小数'), ('str', '字符串')], max_length=64, verbose_name='数据类型')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '监控项表',
            },
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='模板名称')),
                ('applications', models.ManyToManyField(to='monitor_data.Applications', verbose_name='所属应用集')),
            ],
            options={
                'verbose_name_plural': '模板表',
            },
        ),
        migrations.AddField(
            model_name='hostsgroups',
            name='templates',
            field=models.ManyToManyField(to='monitor_data.Templates', verbose_name='所属模板'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='hosts_groups',
            field=models.ManyToManyField(blank=True, to='monitor_data.HostsGroups', verbose_name='所属主机组'),
        ),
        migrations.AddField(
            model_name='hosts',
            name='templates',
            field=models.ManyToManyField(blank=True, to='monitor_data.Templates', verbose_name='所属模板'),
        ),
        migrations.AddField(
            model_name='applications',
            name='items',
            field=models.ManyToManyField(to='monitor_data.Items', verbose_name='所属监控项'),
        ),
    ]
