# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-03 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerexpression',
            name='data_calc_func',
            field=models.CharField(choices=[('avg', '平均值'), ('last', '最近的值')], max_length=64, verbose_name='数据运算函数'),
        ),
    ]
