# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-12 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0002_auto_20180312_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='items',
            field=models.ManyToManyField(blank=True, to='monitor_data.Items', verbose_name='所属监控项'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='applications',
            field=models.ManyToManyField(blank=True, to='monitor_data.Applications', verbose_name='所属应用集'),
        ),
    ]
