# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-04 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0002_auto_20180503_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='monitor_by',
            field=models.CharField(choices=[('agent', '客户端'), ('snmp', 'SNMP'), ('api', 'API')], max_length=64, verbose_name='监控方式'),
        ),
    ]
