# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-24 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0002_auto_20180420_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerexpression',
            name='specified_item_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='只监控专门指定的指标key'),
        ),
    ]
