# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0003_triggerexpression_specified_item_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, '报警事件'), (1, '维护事件')], default=0, verbose_name='事件类型')),
                ('log', models.TextField(blank=True, null=True, verbose_name='日志')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_data.Host', verbose_name='所属主机')),
                ('triggers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor_data.Trigger', verbose_name='所属触发器')),
            ],
            options={
                'verbose_name_plural': '事件日志表',
            },
        ),
    ]
