# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_data', '0003_auto_20180313_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='数据单位'),
        ),
    ]
