# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-10 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0004_items_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='templates',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostname',
            field=models.CharField(help_text='agen输入cmdb客户端配置文件中hostname，snmp输入管理IP', max_length=64, unique=True, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP'),
        ),
    ]
