# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-08 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0006_auto_20180508_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='recover_message',
        ),
        migrations.RemoveField(
            model_name='action',
            name='recover_subject',
        ),
        migrations.AddField(
            model_name='action',
            name='recover_msg_format',
            field=models.TextField(default='主机:{hostname}\nIP:{ip}\n应用集:{name},问题恢复\n内容:{msg}\n开始时间:{start_time}\n持续时间:{duration}\n恢复时间:{recover_time}', verbose_name='恢复通知格式'),
        ),
    ]
