# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_data', '0007_triggerexpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerexpression',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
