# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0007_auto_20180508_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='recover_msg_format',
            field=models.TextField(default='主机:{hostname}\nIP:{ip}\n应用集:{name}\n内容:{msg},问题恢复\n开始时间:{start_time}\n持续时间:{duration}\n恢复时间:{recover_time}', verbose_name='恢复通知格式'),
        ),
        migrations.AlterField(
            model_name='actionoperation',
            name='msg_format',
            field=models.TextField(default='主机:{hostname}\nIP:{ip}\n应用集:{name}\n内容:{msg},存在问题\n开始时间:{start_time}\n持续时间:{duration}', verbose_name='消息格式'),
        ),
    ]
