# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0008_triggerexpression_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='报警策略名称')),
                ('interval', models.IntegerField(default=300, verbose_name='报警间隔(s)')),
                ('recover_notice', models.BooleanField(default=True, verbose_name='故障恢复后是否发送通知')),
                ('recover_subject', models.CharField(blank=True, max_length=128, null=True, verbose_name='恢复通知主题')),
                ('recover_message', models.TextField(blank=True, null=True, verbose_name='恢复通知内容')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('triggers', models.ManyToManyField(to='monitor_data.Trigger', verbose_name='所属触发器')),
            ],
            options={
                'verbose_name_plural': '报警策略表',
            },
        ),
        migrations.CreateModel(
            name='ActionOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('email', '邮件'), ('sms', '短信'), ('weixin', '微信'), ('script', '脚本')], default='email', max_length=64, verbose_name='动作类型')),
                ('step', models.IntegerField(verbose_name='报警升级阈值')),
                ('script_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='脚本名称')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('notifiers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name_plural': '报警动作表',
            },
        ),
        migrations.AddField(
            model_name='triggerexpression',
            name='data_calc_func',
            field=models.CharField(choices=[('avg', '平均值'), ('max', '最大值'), ('min', '最小值'), ('hit', 'HIT'), ('last', '最近的值')], default='last', max_length=64, verbose_name='数据运算函数'),
        ),
        migrations.AddField(
            model_name='triggerexpression',
            name='data_calc_func_args',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='数据运算函数的非固定参数,json格式'),
        ),
    ]
