# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0009_auto_20180510_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionoperation',
            name='msg_format',
        ),
        migrations.AddField(
            model_name='action',
            name='alert_msg_format',
            field=models.TextField(default='主机:{hostname}\nIP:{ip}\n应用集:{name}\n内容:{msg},存在问题\n开始时间:{start_time}\n持续时间:{duration}', verbose_name='报警通知格式'),
        ),
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(help_text='Agent方式要与cmdb客户端配置文件中hostname一致，SNMP、API输入管理IP', max_length=64, unique=True, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='templates',
            field=models.ManyToManyField(blank=True, to='monitor_data.Template', verbose_name='所属模板'),
        ),
    ]
