# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monitor_data', '0009_auto_20180418_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(to='monitor_data.ActionOperation', verbose_name='所属报警动作'),
        ),
        migrations.AddField(
            model_name='actionoperation',
            name='msg_format',
            field=models.TextField(default='主机({hostname},{ip}) 应用集({name})存在问题,内容:{msg}', verbose_name='消息格式'),
        ),
        migrations.AddField(
            model_name='actionoperation',
            name='name',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='报警动作名称'),
            preserve_default=False,
        ),
    ]
