# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-11 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0010_auto_20180511_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
