# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-08 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0011_eventlog_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用'),
        ),
    ]
