# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0012_auto_20180608_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='recover_notice',
            field=models.BooleanField(default=False, verbose_name='故障恢复后是否发送通知'),
        ),
    ]
