# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-11 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0013_auto_20180611_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='action',
            name='recover_notice',
            field=models.BooleanField(default=True, verbose_name='故障恢复后是否发送通知'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
