# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0015_auto_20180611_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'permissions': (('can_show_host', '可访问主机页面'), ('can_show_add_host', '可访问创建主机页面'), ('can_add_host', '可创建主机'), ('can_del_host', '可删除主机'), ('can_show_edit_host', '可访问编辑主机页面'), ('can_edit_host', '可编辑主机')), 'verbose_name_plural': '主机表'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('can_show_user', '可访问用户页面'), ('can_show_add_user', '可访问创建用户页面'), ('can_add_user', '可创建用户'), ('can_del_user', '可删除用户'), ('can_show_edit_user', '可访问编辑用户页面'), ('can_edit_user', '可编辑用户'), ('can_show_change_pass_user', '可访问重置密码页面'), ('can_change_pass_user', '可重置密码'), ('can_show_change_permission_user', '可访问修改权限页面'), ('can_change_permission_user', '可修改权限')), 'verbose_name_plural': '用户表'},
        ),
    ]
