# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0017_auto_20180613_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'permissions': (('can_show_template', '可访问模板页面'), ('can_show_add_template', '可访问创建模板页面'), ('can_add_template', '可创建模板'), ('can_del_template', '可删除模板'), ('can_show_edit_template', '可访问编辑模板页面'), ('can_edit_template', '可编辑模板')), 'verbose_name_plural': '模板表'},
        ),
    ]
