# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0018_auto_20180613_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'permissions': (('can_show_trigger', '可访问触发器页面'), ('can_show_add_trigger', '可访问创建触发器页面'), ('can_add_trigger', '可创建触发器'), ('can_del_trigger', '可删除触发器'), ('can_show_edit_trigger', '可访问编辑触发器页面'), ('can_edit_trigger', '可编辑触发器')), 'verbose_name_plural': '触发器表'},
        ),
    ]
