# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 07:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0019_auto_20180613_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'permissions': (('can_show_action', '可访问报警策略页面'), ('can_show_add_action', '可访问创建报警策略页面'), ('can_add_action', '可创建报警策略'), ('can_del_action', '可删除报警策略'), ('can_show_edit_action', '可访问编辑报警策略页面'), ('can_edit_action', '可编辑报警策略')), 'verbose_name_plural': '报警策略表'},
        ),
    ]
