# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-13 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0020_auto_20180613_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionoperation',
            options={'permissions': (('can_show_action_operation', '可访问报警动作页面'), ('can_show_add_action_operation', '可访问创建报警动作页面'), ('can_add_action_operation', '可创建报警动作'), ('can_del_action_operation', '可删除报警动作'), ('can_show_edit_action_operation', '可访问编辑报警动作页面'), ('can_edit_action_operation', '可编辑报警动作')), 'verbose_name_plural': '报警动作表'},
        ),
    ]
