# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0021_auto_20180613_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='图表名称')),
                ('chart_type', models.CharField(choices=[('line', '线型图'), ('area', '面积图'), ('pie', '饼图')], max_length=64, verbose_name='图表类型')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('templates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor_data.Template', verbose_name='所属模板')),
            ],
            options={
                'verbose_name_plural': '图表',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='data_unit',
            field=models.CharField(choices=[('', '无'), ('KB', 'KB'), ('MB', 'MB'), ('GB', 'GB'), ('%', '百分比'), ('KB/s', 'KB/s'), ('MB/s', 'MB/s')], default='', max_length=64, verbose_name='数据单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chart',
            name='times',
            field=models.ManyToManyField(to='monitor_data.Item', verbose_name='所属监控项'),
        ),
    ]
