# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0023_auto_20180614_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_type',
            field=models.CharField(choices=[('int', '整数'), ('float', '小数')], default='', max_length=64, verbose_name='数据类型'),
            preserve_default=False,
        ),
    ]
