# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0026_auto_20180614_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chart',
            options={'permissions': (('can_show_chart', '可访问图表页面'), ('can_show_add_chart', '可访问创建图表页面'), ('can_add_chart', '可创建图表'), ('can_del_chart', '可删除图表'), ('can_show_edit_chart', '可访问编辑图表页面'), ('can_edit_chart', '可编辑图表')), 'verbose_name_plural': '图表'},
        ),
    ]
