# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-14 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0027_auto_20180614_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chart',
            old_name='times',
            new_name='items',
        ),
    ]
