# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0028_auto_20180614_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='applications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='monitor_data.Application', verbose_name='所属应用集'),
            preserve_default=False,
        ),
    ]
