# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-20 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_data', '0029_chart_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='specified_item_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='只监控专门指定的指标key'),
        ),
    ]
